import '@mantine/core/styles.css'
import './globals.css'

import { Montserrat } from 'next/font/google'
import type { Metadata } from 'next'
import { createTheme, MantineProvider } from '@mantine/core'

import HeaderPage from '@/components/layouts/header/HeaderPage'

const theme = createTheme({
  fontFamily: 'Open Sans, sans-serif',
  primaryColor: 'cyan',
})

const montserrat = Montserrat({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <MantineProvider theme={theme} defaultColorScheme="dark">
          <HeaderPage />
          {children}
        </MantineProvider>
      </body>
    </html>
  )
}
